controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

default:
    path: /
    controller: App\Controller\MatchesController::index